import { Merchant, Product, AgentIdentity } from './types';
import { hashString } from './crypto';

export const INITIAL_AGENTS: AgentIdentity[] = [
  {
    id: 'agent_travel_01',
    name: 'Atlas Autonomous Travel Concierge',
    type: 'autonomous_planner',
    publicKey: 'pk_agent_atlas_98f41e0a29b3c',
    reputationScore: 0.99,
    status: 'active',
  },
  {
    id: 'agent_procurement_02',
    name: 'Nexus Enterprise Buyer',
    type: 'b2b_procurement',
    publicKey: 'pk_agent_nexus_77a10cb55e921',
    reputationScore: 0.95,
    status: 'active',
  },
];

export const INITIAL_MERCHANTS: Merchant[] = [
  {
    id: 'merch_nippon_air',
    name: 'Nippon Skyways Airways',
    category: 'airline',
    destination: 'Japan',
    identityHash: hashString('merch_nippon_air_auth_id_verified_2026'),
    publicKey: 'pk_merch_nippon_981a',
    securityPolicy: {
      maxTransactionAmount: 2500,
      authorizationLifetimeSeconds: 60,
      allowedAgentTypes: ['autonomous_planner', 'b2b_procurement'],
      requireFreshAuthorization: true,
      allowedCurrencies: ['USD', 'JPY'],
    },
  },
  {
    id: 'merch_tokyo_hyatt',
    name: 'Grand Horizon Tokyo & Kyoto Ryokan',
    category: 'hotel',
    destination: 'Japan',
    identityHash: hashString('merch_tokyo_hyatt_verified_2026'),
    publicKey: 'pk_merch_hyatt_432b',
    securityPolicy: {
      maxTransactionAmount: 2000,
      authorizationLifetimeSeconds: 60,
      allowedAgentTypes: ['autonomous_planner'],
      requireFreshAuthorization: true,
      allowedCurrencies: ['USD', 'JPY'],
    },
  },
  {
    id: 'merch_jr_shinkansen',
    name: 'Japan Rail Shinkansen Network',
    category: 'transport',
    destination: 'Japan',
    identityHash: hashString('merch_jr_shinkansen_verified_2026'),
    publicKey: 'pk_merch_shinkansen_710c',
    securityPolicy: {
      maxTransactionAmount: 800,
      authorizationLifetimeSeconds: 60,
      allowedAgentTypes: ['autonomous_planner', 'b2b_procurement'],
      requireFreshAuthorization: true,
      allowedCurrencies: ['USD', 'JPY'],
    },
  },
  {
    id: 'merch_kyoto_heritage',
    name: 'Kyoto Cultural Expeditions & Tea Masters',
    category: 'experience',
    destination: 'Japan',
    identityHash: hashString('merch_kyoto_heritage_verified_2026'),
    publicKey: 'pk_merch_kyoto_882d',
    securityPolicy: {
      maxTransactionAmount: 600,
      authorizationLifetimeSeconds: 60,
      allowedAgentTypes: ['autonomous_planner'],
      requireFreshAuthorization: false,
      allowedCurrencies: ['USD', 'JPY'],
    },
  },
  {
    id: 'merch_ginza_craft',
    name: 'Ginza Artisan & Tech Collective',
    category: 'shopping',
    destination: 'Japan',
    identityHash: hashString('merch_ginza_craft_verified_2026'),
    publicKey: 'pk_merch_ginza_119e',
    securityPolicy: {
      maxTransactionAmount: 1000,
      authorizationLifetimeSeconds: 60,
      allowedAgentTypes: ['autonomous_planner'],
      requireFreshAuthorization: true,
      allowedCurrencies: ['USD', 'JPY'],
    },
  },
];

export const INITIAL_PRODUCTS: Product[] = [
  // Airlines
  {
    id: 'prod_flight_direct_eco',
    merchantId: 'merch_nippon_air',
    merchantName: 'Nippon Skyways Airways',
    category: 'airline',
    destination: 'Japan',
    title: 'Tokyo Direct Flight (Economy SmartFare)',
    description: 'Non-stop flight to Tokyo Narita with priority boarding and carbon-offset voucher.',
    price: 680,
    tier: 'economy',
    inventory: 24,
    tags: ['flight', 'tokyo', 'economy'],
  },
  {
    id: 'prod_flight_direct_lux',
    merchantId: 'merch_nippon_air',
    merchantName: 'Nippon Skyways Airways',
    category: 'airline',
    destination: 'Japan',
    title: 'Tokyo Express Flight (Premium Suite Class)',
    description: 'Lie-flat bed, bespoke dining service, and private lounge access.',
    price: 1350,
    tier: 'luxury',
    inventory: 8,
    tags: ['flight', 'tokyo', 'luxury'],
  },

  // Hotels
  {
    id: 'prod_hotel_tokyo_boutique',
    merchantId: 'merch_tokyo_hyatt',
    merchantName: 'Grand Horizon Tokyo & Kyoto Ryokan',
    category: 'hotel',
    destination: 'Japan',
    title: 'Shibuya Skyline Modern Suite (5 Nights)',
    description: 'Panoramic city view, high-speed mesh Wi-Fi, and complimentary traditional breakfast.',
    price: 650,
    tier: 'standard',
    inventory: 12,
    tags: ['hotel', 'tokyo', 'shibuya', 'modern'],
  },
  {
    id: 'prod_hotel_kyoto_ryokan',
    merchantId: 'merch_tokyo_hyatt',
    merchantName: 'Grand Horizon Tokyo & Kyoto Ryokan',
    category: 'hotel',
    destination: 'Japan',
    title: 'Kyoto Onsen Ryokan Garden Villa (5 Nights)',
    description: 'Private hot spring onsen, tatami rooms, and 7-course seasonal Kaiseki dining.',
    price: 1100,
    tier: 'luxury',
    inventory: 4,
    tags: ['hotel', 'kyoto', 'onsen', 'luxury'],
  },

  // Transport
  {
    id: 'prod_transport_shinkansen_pass',
    merchantId: 'merch_jr_shinkansen',
    merchantName: 'Japan Rail Shinkansen Network',
    category: 'transport',
    destination: 'Japan',
    title: '7-Day Unlimited Shinkansen Green Pass',
    description: 'High-speed bullet train access across Tokyo, Kyoto, Osaka with reserved seating.',
    price: 260,
    tier: 'standard',
    inventory: 50,
    tags: ['transport', 'shinkansen', 'rail'],
  },
  {
    id: 'prod_transport_metro_unlimited',
    merchantId: 'merch_jr_shinkansen',
    merchantName: 'Japan Rail Shinkansen Network',
    category: 'transport',
    destination: 'Japan',
    title: 'Tokyo & Kansai Metro All-Lines Pass',
    description: 'Contactless digital NFC metro pass for rapid urban transit.',
    price: 90,
    tier: 'economy',
    inventory: 100,
    tags: ['transport', 'metro', 'subway'],
  },

  // Experiences
  {
    id: 'prod_exp_teamlab_fuji',
    merchantId: 'merch_kyoto_heritage',
    merchantName: 'Kyoto Cultural Expeditions & Tea Masters',
    category: 'experience',
    destination: 'Japan',
    title: 'teamLab Immersive Art & Mt. Fuji Alpine Tour',
    description: 'VIP early-access pass to digital art museum followed by private guided day trip to Lake Kawaguchi.',
    price: 210,
    tier: 'standard',
    inventory: 18,
    tags: ['experience', 'art', 'fuji', 'nature'],
  },
  {
    id: 'prod_exp_tea_zen',
    merchantId: 'merch_kyoto_heritage',
    merchantName: 'Kyoto Cultural Expeditions & Tea Masters',
    category: 'experience',
    destination: 'Japan',
    title: 'Gion Private Tea Master Ceremony & Temple Walk',
    description: 'Authentic 400-year-old tea house ritual in Kyoto led by a 15th-generation master.',
    price: 150,
    tier: 'economy',
    inventory: 15,
    tags: ['experience', 'culture', 'tea', 'kyoto'],
  },

  // Shopping / Goods
  {
    id: 'prod_shop_craft_bundle',
    merchantId: 'merch_ginza_craft',
    merchantName: 'Ginza Artisan & Tech Collective',
    category: 'shopping',
    destination: 'Japan',
    title: 'Edo Kiriko Glassware & Matcha Curated Set',
    description: 'Handcrafted artisan crystal glassware and ceremonial Uji matcha box delivered to your stay.',
    price: 140,
    tier: 'standard',
    inventory: 30,
    tags: ['shopping', 'craft', 'matcha'],
  },
  {
    id: 'prod_shop_tech_gadget',
    merchantId: 'merch_ginza_craft',
    merchantName: 'Ginza Artisan & Tech Collective',
    category: 'shopping',
    destination: 'Japan',
    title: 'Akihabara Pocket Translator & e-SIM Kit',
    description: 'Offline neural voice translator device and 50GB high-speed 5G Japan e-SIM.',
    price: 110,
    tier: 'economy',
    inventory: 40,
    tags: ['shopping', 'tech', 'esim'],
  },
];
